  # product servis 
services:
  productsv_db:
    image: postgres:16
    environment:
      POSTGRES_DB: product_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: productservice_db_password
    ports:
      - "5432:5432"
    volumes:
     - productdb_vol:/var/lib/postgresql/data
  ordersv_db:
    image: postgres:16
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: orderservice_db_password
    ports:
      - "5433:5432"
    volumes:
      - orderdb_vol:/var/lib/postgresql/data
volumes:
 productdb_vol: {}
 orderdb_vol: {}